#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fore = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_launcher_background = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int op1 = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int op2 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int op3 = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int splash_background = 2130771976;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int HangmanMine01 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int HangmanMine02 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int HangmanMine03 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int HangmanMine04 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int HangmanMine05 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int HangmanMine06 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int HangmanMine07 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int HangmanMine08 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int HangmanMine09 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int HangmanMine10 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int HangmanMine11 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int HangmanMine12 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int HangmanMine13 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int HangmanMine14 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int hg = 2130837518;
			
			// aapt resource value: 0x7F020010
			public const int icon = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int icr = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int ics = 2130837522;
			
			// aapt resource value: 0x7F02000F
			public const int ic_launcher_round = 2130837519;
			
			// aapt resource value: 0x7F020013
			public const int lostgame = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int splash_screen = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int trophyw = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int tryagainl = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnA = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnAdd = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btnB = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btnC = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int btnD = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int btnE = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int btnF = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int btnG = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int btnH = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int btnI = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int btnJ = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int btnK = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int btnL = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int btnM = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int btnN = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int btnO = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int btnP = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int btnPlay = 2130903057;
			
			// aapt resource value: 0x7F03001C
			public const int btnplayagain = 2130903068;
			
			// aapt resource value: 0x7F030012
			public const int btnQ = 2130903058;
			
			// aapt resource value: 0x7F03001D
			public const int btnquit = 2130903069;
			
			// aapt resource value: 0x7F030013
			public const int btnR = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int btnS = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int btnT = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int btnU = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int btnV = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int btnW = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int btnX = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int btnY = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int btnZ = 2130903067;
			
			// aapt resource value: 0x7F03001E
			public const int cbxDifficult = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int cbxEasy = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int cbxNormal = 2130903072;
			
			// aapt resource value: 0x7F030022
			public const int imgfinal = 2130903074;
			
			// aapt resource value: 0x7F030021
			public const int imgHangman = 2130903073;
			
			// aapt resource value: 0x7F030023
			public const int linearLayout1 = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int linearLayout2 = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int linearLayout3 = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int linearLayout4 = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int listView1 = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int nametxt = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int scoretxt = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int txtDisplay = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int txtName = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int txtplayerName = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int txtscore = 2130903085;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int final_screen = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int list_adapter = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int play_game = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int AppTheme_Splash = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
